/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package window;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author Ali Othman
 */
public class Ui extends javax.swing.JFrame {

    /**
     * Creates new form Ui
     */
    public Ui() {
        initComponents();
    }
    String Name;
    String Bot;
    String input;
    String you;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtBot = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        submitt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtinput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnsend = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(33, 33, 33));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setName(""); // NOI18N

        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Name :");

        txtBot.setText("Bob");
        txtBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBotActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Bot Name :");

        submitt.setBackground(new java.awt.Color(33, 33, 33));
        submitt.setForeground(new java.awt.Color(255, 255, 255));
        submitt.setText("Submit");
        submitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submittActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("ChatBot:V1.7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtBot, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitt)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(52, 52, 52)
                .addComponent(submitt)
                .addGap(80, 80, 80))
        );

        jTabbedPane1.addTab("my informations", jPanel1);

        jPanel2.setEnabled(false);

        jLabel3.setText("say something below :");

        btnsend.setBackground(new java.awt.Color(0, 0, 0));
        btnsend.setForeground(new java.awt.Color(255, 255, 255));
        btnsend.setText("send");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane2.setViewportView(txtArea);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Welcome ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtinput, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsend))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel5)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsend))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Chat Window", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("information");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBotActionPerformed

    private void submittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submittActionPerformed
        // TODO add your handling code here:
        Name = txtName.getText();
        Bot = txtBot.getText();
        if(!Name.equals("")&& !Bot.equals("") ){
        submitt.setText("update");
        btnsend.setEnabled(true);
        txtinput.setEnabled(true);
        submitt.setForeground(Color.black);
        submitt.setBackground(Color.GREEN);
        JOptionPane.showMessageDialog(this, "thanks press on  Chat Window");
    }//GEN-LAST:event_submittActionPerformed
    else{
            JOptionPane.showMessageDialog(this, "the Name Or/And Botname Is empty");
        }}
    
    
    
    
    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        
       // TODO add your handling code here:
        you = Name +": "+txtinput.getText()+"\n";
        input = txtinput.getText().toLowerCase().trim();
        txtinput.setText("");
        txtArea.append(you);
        
        ArrayList<String> intro =new  ArrayList<>();
        intro.add("hi"); intro.add("hello"); intro.add("good morning"); intro.add("good evining");
        
        ArrayList<String> body = new ArrayList<String>();
        body.add("hi"); body.add("hello"); body.add("good morning"); body.add("good evining");
        body.add("age"); body.add("what"); body.add("how"); body.add("where"); body.add("your"); body.add("name");
        body.add("are"); body.add("you"); body.add("favourite"); body.add("food"); body.add("drinks"); body.add("when"); 
        body.add("sleep"); body.add("sleeping"); body.add("eat"); body.add("eating"); body.add("lunch"); body.add("lunching");
        body.add("play"); body.add("playing"); body.add("live");body.add("living"); body.add("nationality"); body.add("study");
        body.add("learn"); body.add("learning"); body.add("studying");body.add("are"); body.add("is"); body.add("am"); 
        body.add("bye"); body.add("thanks"); body.add("thank you"); body.add("why"); body.add("speak");
        body.add("speaking"); body.add("diving"); body.add("swimming");
        body.add("arabic"); body.add("english"); body.add("france");
        body.add("languages"); body.add("speak"); body.add("year"); body.add("you"); body.add("and");
        body.add("yes"); body.add("arithmatic"); body.add("am"); body.add("pm"); body.add("live");
        body.add("a"); body.add("b"); body.add("c");body.add("d"); body.add("e"); body.add("f");
        body.add("operations"); body.add("sum"); body.add("scientists"); body.add("five");
        body.add("mothor"); body.add("father"); body.add("brothor");body.add("sister"); body.add("grand father"); body.add("grand mothor");
        
        
        if(input.length() > 0 ){
//        for (int i=0 ; i<intro.size(); i++){
//        if(input.contains(intro.get(i))){
//        txtArea.append(Bot + " :" + intro.get(i) +" "+getRandomRequest() +"\n");
//        break;
//        }}
        for(int i = 0 ; i<body.size();i++){
        if(input.contains(body.get(i))){
        break;
        }
        }getresponse(input);}
          if (input.length() == 0){
         txtArea.append(Bot + " :" + "Say something, please."+ "\n");
        }
//          else {
//           txtArea.append(Bot + " :" + getRandomResponse()+ "\n");
//         }
         
        
    }//GEN-LAST:event_btnsendActionPerformed
    public  void getresponse (String statement){
        this.input =statement;
        //statement = txtinput.getText().toLowerCase().trim();
      
         if(  input.contains("your")&& input.contains( "age") || input.contains("old") )
         txtArea.append(Bot + " :" +  " " +"my age is 40 years old "+" ,"+getRandomRequest()+ "\n");
         else if(  input.contains("year")&& input.contains( "and") && input.contains("you") )
         txtArea.append(Bot + " :" +  " " +"my age is 40 years old "+" ,"+getRandomRequest()+ "\n");
          else if(  input.contains("live")&& input.contains( "and") && input.contains("you") )
         txtArea.append(Bot + " :" +  " " +"iam living on italia "+" ,"+getRandomRequest()+ "\n");
             else if(  input.contains("name") || input.contains("iam")&&
                     input.contains( "and") && input.contains("you")  )
         txtArea.append(Bot + " :" +  " " +" iam "+ Bot+" ,"+getRandomRequest()+ "\n");
             else if(  input.contains("speak") || input.contains("speaking")&&
                     input.contains( "and") && input.contains("you")  )
         txtArea.append(Bot + " :" +  " " +" iam speak english only "+" ,"+getRandomRequest()+ "\n");
             else if(  input.contains("diving") || input.contains("swimming")&&
                     input.contains( "and") && input.contains("you")  )
         txtArea.append(Bot + " :" +  " " +" iam not swim or diving befor "+" ,"+getRandomRequest()+ "\n");
             else if(  input.contains("arabic") || input.contains("france") || input.contains("english")&&
                     input.contains( "and") && input.contains("you")  )
         txtArea.append(Bot + " :" +  " " +" iam speak english "+" ,"+getRandomRequest()+ "\n");
             
         
         else if(statement.contains("what") && statement.contains("your")&& statement.contains("name") )
         txtArea.append(Bot + " :" +  " " +"my name  is "  +Bot+" ," + getRandomRequest()+ "\n");
         
         else if(statement.contains("how") && statement.contains("are")&& statement.contains("you") )
         txtArea.append(Bot + " :" +  " " + " Iam Well , Thank you for Asking "+Name+" ,"+ getRandomRequest()+ "\n");
         
         else if(statement.contains("what") && statement.contains("your")&& statement.contains("favorite") 
                && statement.contains("food"))
         txtArea.append(Bot + " :" +  " " +"my favourite food is spaghity with eggs "+" ,"+ getRandomRequest()+ "\n");
         
         else if(statement.contains("what") && statement.contains("your")&& statement.contains("favorite") 
                && statement.contains("drinks") )
         txtArea.append(Bot + " :" +  " " +"my favourite drinks is  super orio "+" ,"+ getRandomRequest()+ "\n");
         
         else if(statement.contains("when") && statement.contains("sleep") || statement.contains("sleeping"))
         txtArea.append(Bot + " :" +  " " +"iam sleep in 10 pm "+" ,"+  getRandomRequest()+"\n");
         
         else if(statement.contains("when") && statement.contains("eat") || statement.contains("eatung")
                 || statement.contains("lunch") || statement.contains("lunching"))
         txtArea.append(Bot + " :" +  " " +"iam eat at 5 pm "+" ,"+ getRandomRequest()+ "\n");
         
          else if(statement.contains("when") && statement.contains("play") || statement.contains("playing"))
         txtArea.append(Bot + " :" +  " " +"iam playing  at 7 pm "+" ,"+ getRandomRequest()+ "\n");
         
         else if(statement.contains("where") && statement.contains("live") || statement.contains("living"))
         txtArea.append(Bot + " :" +  " " +"iam living   in California "+" ,"+ getRandomRequest()+ "\n");
         
         else if(statement.contains("what") && statement.contains("nationality"))
         txtArea.append(Bot + " :" +  " " +"iam Chinise  "+" ,"+  getRandomRequest()+"\n");
         
         else if(statement.contains("what") && statement.contains("study") || statement.contains("learn")
                 || statement.contains("learning") || statement.contains("studying"))
         txtArea.append(Bot + " :" +  " " +"iam playing no study no learm  "+" ,"+ getRandomRequest()+"\n");
         
         else if(statement.contains("have") && statement.contains("father") || statement.contains("mothor")
                 || statement.contains("father") || statement.contains("brothor") || statement.contains("sisters")
                 || statement.contains("grand father") || statement.contains("grand  mothor") || statement.contains("married"))
         txtArea.append(Bot + " :" +  " " +" yes iam a human like you  "+" ,"+  getRandomRequest()+"\n");
         
         
         
         else if(statement.contains("five"))
         txtArea.append(Bot + " :" +  " " +"you are a smart "+" ,"+  getRandomRequest()+"\n");
        
         else if(statement.contains("hello"))
         txtArea.append(Bot + " :" +  " " +" hello "+" ,"+  getRandomRequest()+"\n");
         else if(statement.contains("good morning"))
         txtArea.append(Bot + " :" +  " " +" good morning "+" ,"+  getRandomRequest()+"\n");
         else if(statement.contains("good evining"))
         txtArea.append(Bot + " :" +  " " +" good evining "+" ,"+  getRandomRequest()+"\n");
         else if(statement.contains("bye") || statement.contains("good bye"))
         txtArea.append(Bot + " :" +  " " +" bye "+ Name+"\n");
         
         else if(statement.contains("thanks") || statement.contains(" thank you ")){
             int decider = (int) (Math.random()*3+1);
                    if(decider == 1){
           txtArea.append(Bot + " :" +  " " +" you are agood person "+" ,"+  "\n");
                    }
                    else if(decider == 2){
          txtArea.append(Bot + " :" +  " " +" No thanks on duty" +" ,"+ "\n");
                    }
                    else if(decider == 3){
          txtArea.append(Bot + " :" +  " " +" you are Respectable human"+" ,"+  getRandomRequest()+"\n");
                    }
                    System.out.println("you are agood person");
                    System.out.println("No thanks on duty");
                    System.out.println("you are Respectable human + question");
                    
         }
         
         else if(statement.contains("why")){
             int decider = (int) (Math.random()*3+1);
                    if(decider == 1){
           txtArea.append(Bot + " :" +  " " +" to be like you  "+" ,"+  getRandomRequest()+"\n");
                    }
                    else if(decider == 2){
          txtArea.append(Bot + " :" +  " " +" because ihave emptiness time" +" ,"+  getRandomRequest()+"\n");
                    }
                    else if(decider == 3){
          txtArea.append(Bot + " :" +  " " +" inquisitiveness "+" ,"+  getRandomRequest()+"\n");
                    }
         }
         
         else if(statement.contains("languages") || statement.contains("speak"))
         txtArea.append(Bot + " :" +  " " +" iam speak english  "+" ,"+  getRandomRequest()+"\n");
         else if(statement.contains("arithmatic") || statement.contains("operation") || 
                 statement.contains("operations") || statement.contains("sum") )
         txtArea.append(Bot + " :" +  " " +" arithmatic operation is a funny "+" ,"+  getRandomRequest()+"\n");
         else if(statement.contains("yes"))
         txtArea.append(Bot + " :" +  " " +" that is good thing "+" ,"+  getRandomRequest()+"\n");
         else if(statement.contains("hi"))
         txtArea.append(Bot + " :" +  " " +" hi "+" ,"+  getRandomRequest()+"\n");
         else if(statement.contains("am") || statement.contains("pm"))
         txtArea.append(Bot + " :" +  " " +"ok , thanks  "+" ,"+  getRandomRequest()+"\n");
          else if(statement.contains("c"))
         txtArea.append(Bot + " :" +  " " +" that is a correct answer"+" ,"+  getRandomRequest()+"\n");
//          else if(statement.contains("a") || statement.contains("b") || statement.contains("d")
//                 || statement.contains("e") || statement.contains("f")) 
//         txtArea.append(Bot + " :" +  " " +" that is a wrong answer"+" ,"+  getRandomRequest()+"\n");
         
         else{
           //  String randoom = getRandomResponse();
         String r = getRandomRequest();
              txtArea.append(Bot + " :" + r+ "\n");
         }
         
    }
    
    public String getRandomResponse(){
        final int NUMBER_OF_RESPONSES = 6;
        double r = Math.random();
        int whichResponse = (int) (r * NUMBER_OF_RESPONSES);
        String response = "";
        if (whichResponse == 0)
        {
            response = "Interesting, tell me more.";
        }
        else if (whichResponse == 1)
        {
            response = "Hmmm.";
        }
        else if (whichResponse == 2)
        {
            response = "Do you really think so?";
        }
        else if (whichResponse == 3)
        {
            response = "Please rephrase that";
        }
        else if(whichResponse == 4)
        {
            response = "What do you mean?";
        }
        else if(whichResponse == 5)
        {
            response = "I don't understand. Explain, please.";
        }
          
        return response;
    } 
  
     public String getRandomRequest(){
        final int NUMBER_OF_REQUESTS = 10;
        double r = Math.random();
        int whichRequest = (int) (r * NUMBER_OF_REQUESTS);
        String request = "";
        if (whichRequest == 0)
        {
            request = "Are you real?";
        }
        else if (whichRequest == 1)
        {
            request = "What is your name?";
        }
        else if (whichRequest == 2)
        {
            request = "Where do you live?";
        }
        else if (whichRequest == 3)
        {
            request = "How old are you?";
        }
        else if(whichRequest == 4)
        {
            request = "How can you i help you?";
        }
        else if(whichRequest == 5)
        {
            request = "Which languages do you speak arabic or english or franc?";
        }
        else if (whichRequest == 6)
        {
            request = "How are you? Are you doing ok?";
        }
        else if (whichRequest == 7)
        {
            request = "What time is it?";
        }
        else if(whichRequest == 8)
        {
            request = "What are your hobbies swimming or diving?";
        }
        else if(whichRequest == 9)
        {
            request = "What do you look like of the artisters?";
        } 
        else if(whichRequest == 10)
        {
            request = "How much is three plus two?";
        }
        else if(whichRequest == 11)
        {
            request = "are you love Mango Juice?";
        }
          
        return request;
    } 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton submitt;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtBot;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtinput;
    // End of variables declaration//GEN-END:variables

    private String words(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
